### ISSUE TITLE
Add README file with Links to articles sources

### ISSUE THREAD

**Issue by urboom** [urboom/BSA-JS#3]

**Comment by volodymyr-kushnir** [comment]
@urboom а можна відкрити цей **issue** ще раз, поправити **README.md** в приблизно такий вигляд (в теперішньому варіанті блокквоти лишні, на мій погляд)
```
## Binary Studio Academy 2017
* [**A User's Guide to Rational Thinking**](...)
* [**Brain Activity**](...)
```
і закоммітити це все назад з повідомленням **"Remove blockquotes (fixes #3)"**?
**GitHub** закриє цей issue автоматично, бо *fixes #3*.

**Comment by urboom** [comment]
@volodymyr-kushnir Дякую за підказку!
